FROM tomcat:9.0

RUN rm -rf /usr/local/tomcat/webapps/*

COPY eidiko_workorder.war /usr/local/tomcat/webapps/eidiko_workorder.war
COPY  target/eidiko-workorder-integration-service.war /usr/local/tomcat/webapps/integration.war
COPY  target/eidiko-workorder-details-schedular.war /usr/local/tomcat/webapps/schedular.war

EXPOSE 8080

CMD ["catalina.sh", "run"]

