FROM tomcat:9.0

RUN rm -rf /usr/local/tomcat/webapps/*

COPY eidiko_workorder.war /usr/local/tomcat/webapps/eidiko_workorder.war
COPY eidiko-workorder-integration-service.war /usr/local/tomcat/webapps/eidiko-workorder-integration-service.war
COPY eidiko-workorder-details-schedular.war /usr/local/tomcat/webapps/eidiko-workorder-details-schedular.war

EXPOSE 8080

CMD ["catalina.sh", "run"]

